import type { Frame } from "../types/interface";

export const sampleData: Frame[] = [
  {
    id: 1,
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Large",
    price: 200,
    quantity: 50,
  },
  {
    id: 2,
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    id: 3,
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    id: 4,
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Oval",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    id: 5,
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    id: 6,
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    id: 7,
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    id: 8,
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    id: 9,
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    id: 10,
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    id: 11,
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    id: 12,
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    id: 13,
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    id: 14,
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    id: 15,
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    id: 16,
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    id: 17,
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    id: 18,
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    id: 19,
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    id: 20,
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    id: 21,
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    id: 22,
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    id: 23,
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    id: 24,
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    id: 25,
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    id: 26,
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    id: 27,
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    id: 28,
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    id: 29,
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    id: 30,
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    id: 31,
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    id: 32,
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    id: 33,
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    id: 34,
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    id: 35,
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    id: 36,
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    id: 37,
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    id: 38,
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    id: 39,
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    id: 40,
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    id: 41,
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    id: 42,
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    id: 43,
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    id: 44,
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    id: 45,
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    id: 46,
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    id: 47,
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    id: 48,
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    id: 49,
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    id: 50,
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    id: 51,
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    id: 52,
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    id: 53,
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    id: 54,
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    id: 55,
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    id: 56,
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    id: 57,
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    id: 58,
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    id: 59,
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    id: 60,
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    id: 61,
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    id: 62,
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    id: 63,
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    id: 64,
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    id: 65,
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    id: 66,
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    id: 67,
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    id: 68,
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    id: 69,
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    id: 70,
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    id: 71,
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    id: 72,
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    id: 73,
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    id: 74,
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    id: 75,
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    id: 76,
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    id: 77,
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    id: 78,
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    id: 79,
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    id: 80,
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    id: 81,
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    id: 82,
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    id: 83,
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    id: 84,
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    id: 85,
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    id: 86,
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    id: 87,
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    id: 88,
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    id: 89,
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    id: 90,
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },

  // add more sample data here...
];
