import type { ContactLens, Frame, Lens } from "../types/interface";

export const sampleData: Frame[] = [
  {
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Large",
    price: 200,
    quantity: 50,
  },
  {
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Oval",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },
  {
    name: "Stylish Sunglasses",
    type: "Sunglasses",
    material: "Acetate",
    shape: "Round",
    color: "Black",
    size: "Medium",
    price: 200,
    quantity: 50,
  },
  {
    name: "Classic Eyeglasses",
    type: "Eyeglasses",
    material: "Metal",
    shape: "Rectangle",
    color: "Silver",
    size: "Large",
    price: 150,
    quantity: 30,
  },
  {
    name: "Trendy Frames",
    type: "Eyeglasses",
    material: "Plastic",
    shape: "Oval",
    color: "Red",
    size: "Small",
    price: 120,
    quantity: 20,
  },

  // add more sample data here...
];

export const sampleLenseData: Lens[] = [
  {
    name: "Anti-Glare Single Vision Lens",
    description: "Durable single vision lens with anti-reflective coating.",
    purchasePrice: 120,
    salesPrice: 120,
    stock: 50,
    category: "lens",
    brand: "Essilor",
    images: [
      "https://res.cloudinary.com/dw57lx7qa/image/upload/v1756815990/products/ok6dj04cmjasmtqjdl2r.jpg",
      "https://res.cloudinary.com/dw57lx7qa/image/upload/v1756815991/products/gnrdak8vpa8j1uf3plei.jpg",
    ],
    lensType: "single vision",
    material: "polycarbonate",
    coatings: ["anti-reflective", "UV protection"],
    prescriptionRange: "+6.00 to -6.00",
    index: 1.6,
    thickness: "Thin cut",
    color: "clear",
    diameter: 70,
    warranty: "1 year",
    deliveryTime: "3-5 business days",
    offer: 10,
    rating: 4.5,
  },
  {
    name: "Blue Light Blocking Lens",
    description: "Protects eyes from digital screen blue light.",
    purchasePrice: 150,
    salesPrice: 200,
    stock: 40,
    category: "lens",
    brand: "Hoya",
    images: [
      "https://res.cloudinary.com/dw57lx7qa/image/upload/v1756817001/products/bluelight1.jpg",
      "https://res.cloudinary.com/dw57lx7qa/image/upload/v1756817002/products/bluelight2.jpg",
    ],
    lensType: "single vision",
    material: "trivex",
    coatings: ["blue light filter", "scratch-resistant"],
    prescriptionRange: "+4.00 to -4.00",
    index: 1.56,
    thickness: "Standard",
    color: "clear",
    diameter: 65,
    warranty: "1 year",
    deliveryTime: "4-6 business days",
    offer: 15,
    rating: 4.8,
  },
  {
    name: "Photochromic Transition Lens",
    description: "Automatically darkens under sunlight for comfort.",
    purchasePrice: 150,
    salesPrice: 180,
    stock: 30,
    category: "lens",
    brand: "Zeiss",
    images: [
      "https://res.cloudinary.com/dw57lx7qa/image/upload/v1756817101/products/photochromic1.jpg",
      "https://res.cloudinary.com/dw57lx7qa/image/upload/v1756817102/products/photochromic2.jpg",
    ],
    lensType: "progressive",
    material: "polycarbonate",
    coatings: ["photochromic", "anti-reflective"],
    prescriptionRange: "+5.00 to -5.00",
    index: 1.6,
    thickness: "Thin cut",
    color: "clear to grey",
    diameter: 70,
    warranty: "2 years",
    deliveryTime: "5-7 business days",
    offer: 12,
    rating: 4.6,
  },
  {
    name: "Polarized Sunglass Lens",
    description: "Blocks glare and enhances outdoor vision.",
    purchasePrice: 100,
    salesPrice: 120,
    stock: 25,
    category: "lens",
    brand: "Ray-Ban",
    images: [
      "https://res.cloudinary.com/dw57lx7qa/image/upload/v1756817201/products/polarized1.jpg",
      "https://res.cloudinary.com/dw57lx7qa/image/upload/v1756817202/products/polarized2.jpg",
    ],
    lensType: "sunglass",
    material: "polycarbonate",
    coatings: ["polarized", "scratch-resistant"],
    prescriptionRange: "+2.00 to -2.00",
    index: 1.5,
    thickness: "Standard",
    color: "dark grey",
    diameter: 70,
    warranty: "6 months",
    deliveryTime: "3-5 business days",
    offer: 5,
    rating: 4.4,
  },
  {
    name: "High-Index 1.67 Lens",
    description: "Ultra-thin lens ideal for strong prescriptions.",
    purchasePrice: 220,
    salesPrice: 250,
    stock: 20,
    category: "lens",
    brand: "Essilor",
    images: [
      "https://res.cloudinary.com/dw57lx7qa/image/upload/v1756817301/products/highindex1.jpg",
      "https://res.cloudinary.com/dw57lx7qa/image/upload/v1756817302/products/highindex2.jpg",
    ],
    lensType: "single vision",
    material: "high-index",
    coatings: ["anti-reflective", "UV protection"],
    prescriptionRange: "+8.00 to -8.00",
    index: 1.67,
    thickness: "Ultra thin",
    color: "clear",
    diameter: 70,
    warranty: "2 years",
    deliveryTime: "7-10 business days",
    offer: 20,
    rating: 4.9,
  },
  {
    name: "Bifocal Lens",
    description: "Traditional bifocal design with two segments.",
    purchasePrice: 120,
    salesPrice: 160,
    stock: 35,
    category: "lens",
    brand: "Hoya",
    images: [
      "https://res.cloudinary.com/dw57lx7qa/image/upload/v1756817401/products/bifocal1.jpg",
      "https://res.cloudinary.com/dw57lx7qa/image/upload/v1756817402/products/bifocal2.jpg",
    ],
    lensType: "bifocal",
    material: "trivex",
    coatings: ["anti-scratch", "UV protection"],
    prescriptionRange: "+5.00 to -5.00",
    index: 1.56,
    thickness: "Standard",
    color: "clear",
    diameter: 70,
    warranty: "1 year",
    deliveryTime: "4-6 business days",
    offer: 8,
    rating: 4.3,
  },
  {
    name: "Kids Impact-Resistant Lens",
    description: "Extra durable lenses for children’s eyewear.",
    purchasePrice: 100,
    salesPrice: 190,
    stock: 45,
    category: "lens",
    brand: "Essilor Junior",
    images: [
      "https://res.cloudinary.com/dw57lx7qa/image/upload/v1756817501/products/kidslens1.jpg",
      "https://res.cloudinary.com/dw57lx7qa/image/upload/v1756817502/products/kidslens2.jpg",
    ],
    lensType: "single vision",
    material: "polycarbonate",
    coatings: ["scratch-resistant", "UV protection"],
    prescriptionRange: "+3.00 to -3.00",
    index: 1.5,
    thickness: "Standard",
    color: "clear",
    diameter: 65,
    warranty: "1 year",
    deliveryTime: "3-5 business days",
    offer: 10,
    rating: 4.7,
  },
  {
    name: "Aspheric Lens",
    description: "Slim design reduces distortion for a natural look.",
    purchasePrice: 120,
    salesPrice: 190,
    stock: 28,
    category: "lens",
    brand: "Zeiss",
    images: [
      "https://res.cloudinary.com/dw57lx7qa/image/upload/v1756817601/products/aspheric1.jpg",
      "https://res.cloudinary.com/dw57lx7qa/image/upload/v1756817602/products/aspheric2.jpg",
    ],
    lensType: "single vision",
    material: "high-index",
    coatings: ["anti-reflective", "scratch-resistant"],
    prescriptionRange: "+6.00 to -6.00",
    index: 1.6,
    thickness: "Thin cut",
    color: "clear",
    diameter: 70,
    warranty: "2 years",
    deliveryTime: "5-7 business days",
    offer: 10,
    rating: 4.6,
  },
  {
    name: "Progressive Lens",
    description: "No-line multifocal lenses for all-day vision comfort.",
    purchasePrice: 190,
    salesPrice: 280,
    stock: 15,
    category: "lens",
    brand: "Hoya",
    images: [
      "https://res.cloudinary.com/dw57lx7qa/image/upload/v1756817701/products/progressive1.jpg",
      "https://res.cloudinary.com/dw57lx7qa/image/upload/v1756817702/products/progressive2.jpg",
    ],
    lensType: "progressive",
    material: "trivex",
    coatings: ["anti-reflective", "UV protection"],
    prescriptionRange: "+5.00 to -5.00",
    index: 1.6,
    thickness: "Thin cut",
    color: "clear",
    diameter: 70,
    warranty: "2 years",
    deliveryTime: "7-10 business days",
    offer: 18,
    rating: 4.9,
  },
  {
    name: "Sports Performance Lens",
    description: "Designed for athletes with impact resistance.",
    purchasePrice: 190,
    salesPrice: 320,
    stock: 22,
    category: "lens",
    brand: "Oakley",
    images: [
      "https://res.cloudinary.com/dw57lx7qa/image/upload/v1756817801/products/sports1.jpg",
      "https://res.cloudinary.com/dw57lx7qa/image/upload/v1756817802/products/sports2.jpg",
    ],
    lensType: "sunglass",
    material: "polycarbonate",
    coatings: ["polarized", "scratch-resistant"],
    prescriptionRange: "+4.00 to -4.00",
    index: 1.5,
    thickness: "Standard",
    color: "brown tint",
    diameter: 68,
    warranty: "1 year",
    deliveryTime: "3-5 business days",
    offer: 12,
    rating: 4.8,
  },
  {
    name: "Tinted Fashion Lens",
    description: "Stylish tinted lenses for a trendy look.",
    purchasePrice: 120,
    salesPrice: 190,
    stock: 38,
    category: "lens",
    brand: "Generic",
    images: [
      "https://res.cloudinary.com/dw57lx7qa/image/upload/v1756817901/products/tinted1.jpg",
      "https://res.cloudinary.com/dw57lx7qa/image/upload/v1756817902/products/tinted2.jpg",
    ],
    lensType: "fashion",
    material: "plastic",
    coatings: ["scratch-resistant"],
    prescriptionRange: "Plano",
    index: 1.5,
    thickness: "Standard",
    color: "light pink",
    diameter: 65,
    warranty: "6 months",
    deliveryTime: "3-5 business days",
    offer: 5,
    rating: 4.2,
  },
];

export const contactLenses: ContactLens[] = [
  {
    name: "Acuvue Oasys 1-Day",
    brand: "Acuvue",
    type: "daily disposable",
    color: "brown",
    material: "Senofilcon A",
    waterContent: "38%",
    diameter: 14.3,
    baseCurve: 8.5,
    powerRange: "-12.00 to +8.00",
    uvProtection: true,
    purchasePrice: 20,
    salesPrice: 55,
    stock: 120,
    offer: 10,
    rating: 4.7,
    description:
      "Comfortable daily disposable lenses with UV protection and moisture lock technology.",
    images: [
      "https://res.cloudinary.com/demo/image/upload/contactlens/acuvue_oasys_1day_1.jpg",
      "https://res.cloudinary.com/demo/image/upload/contactlens/acuvue_oasys_1day_2.jpg",
    ],
  },
  {
    name: "Bausch + Lomb Ultra",
    brand: "Bausch + Lomb",
    type: "monthly",
    color: "brown tint",
    material: "Samfilcon A",
    waterContent: "46%",
    diameter: 14.2,
    baseCurve: 8.6,
    powerRange: "-12.00 to +6.00",
    uvProtection: false,
    purchasePrice: 20,
    salesPrice: 60,
    stock: 80,
    offer: 15,
    rating: 4.5,
    description:
      "Monthly contact lenses with MoistureSeal technology for all-day comfort.",
    images: [
      "https://res.cloudinary.com/demo/image/upload/contactlens/bausch_ultra_1.jpg",
    ],
  },
  {
    name: "Air Optix HydraGlyde",
    brand: "Alcon",
    type: "monthly",
    color: "tint",
    material: "Lotrafilcon B",
    waterContent: "33%",
    diameter: 14.2,
    baseCurve: 8.6,
    powerRange: "-10.00 to +6.00",
    uvProtection: false,
    purchasePrice: 20,
    salesPrice: 70,
    stock: 95,
    offer: 5,
    rating: 4.6,
    description:
      "Breathable monthly lenses with HydraGlyde moisture matrix for long-lasting hydration.",
    images: [
      "https://res.cloudinary.com/demo/image/upload/contactlens/airoptix_hydraglyde_1.jpg",
    ],
  },
  {
    name: "Dailies AquaComfort Plus",
    brand: "Alcon",
    type: "daily disposable",
    color: "golden red",
    material: "Nelfilcon A",
    waterContent: "69%",
    diameter: 14.0,
    baseCurve: 8.7,
    powerRange: "-15.00 to +8.00",
    uvProtection: false,
    purchasePrice: 20,
    salesPrice: 80,
    stock: 150,
    offer: 0,
    rating: 4.4,
    description:
      "Daily lenses with blink-activated moisture technology for consistent comfort.",
    images: [
      "https://res.cloudinary.com/demo/image/upload/contactlens/dailies_aquacomfort_1.jpg",
    ],
  },
  {
    name: "CooperVision Biofinity",
    brand: "CooperVision",
    type: "monthly",
    color: "green",
    material: "Comfilcon A",
    waterContent: "48%",
    diameter: 14.0,
    baseCurve: 8.6,
    powerRange: "-12.00 to +8.00",
    uvProtection: false,
    purchasePrice: 20,
    salesPrice: 100,
    stock: 110,
    offer: 12,
    rating: 4.8,
    description:
      "Highly breathable silicone hydrogel lenses for extended wear comfort.",
    images: [
      "https://res.cloudinary.com/demo/image/upload/contactlens/biofinity_1.jpg",
    ],
  },
  {
    name: "Acuvue Vita",
    brand: "Acuvue",
    type: "monthly",
    color: "gray",
    material: "Senofilcon C",
    waterContent: "41%",
    diameter: 14.0,
    baseCurve: 8.4,
    powerRange: "-12.00 to +8.00",
    uvProtection: true,
    purchasePrice: 20,
    salesPrice: 40,
    stock: 70,
    offer: 8,
    rating: 4.3,
    description:
      "Monthly contact lens with HydraMax technology for all-month comfort.",
    images: [
      "https://res.cloudinary.com/demo/image/upload/contactlens/acuvue_vita_1.jpg",
    ],
  },
  {
    name: "Clariti 1 Day",
    brand: "CooperVision",
    type: "daily disposable",
    color: "blue",
    material: "Somofilcon A",
    waterContent: "56%",
    diameter: 14.1,
    baseCurve: 8.6,
    powerRange: "-10.00 to +8.00",
    uvProtection: true,
    purchasePrice: 20,
    salesPrice: 75,
    stock: 130,
    offer: 0,
    rating: 4.5,
    description:
      "Affordable daily contact lens with silicone hydrogel and UV blocking.",
    images: [
      "https://res.cloudinary.com/demo/image/upload/contactlens/clariti_1day_1.jpg",
    ],
  },
  {
    name: "FreshLook Colorblends",
    brand: "Alcon",
    type: "monthly (colored)",
    color: "brown tint",
    material: "Phemfilcon A",
    waterContent: "55%",
    diameter: 14.5,
    baseCurve: 8.6,
    powerRange: "Plano to -8.00",
    uvProtection: false,
    purchasePrice: 20,
    salesPrice: 55,
    stock: 60,
    offer: 20,
    rating: 4.2,
    description:
      "Enhance or change your eye color with natural-looking shades.",
    images: [
      "https://res.cloudinary.com/demo/image/upload/contactlens/freshlook_colorblends_1.jpg",
    ],
  },
  {
    name: "SofLens Daily Disposable",
    brand: "Bausch + Lomb",
    type: "daily disposable",
    color: "yellow orange",
    material: "Hilafilcon B",
    waterContent: "59%",
    diameter: 14.2,
    baseCurve: 8.6,
    powerRange: "-9.00 to +6.50",
    uvProtection: false,
    purchasePrice: 20,
    salesPrice: 55,
    stock: 200,
    offer: 5,
    rating: 4.1,
    description:
      "Comfortable daily contact lens with high-definition optics for crisp vision.",
    images: [
      "https://res.cloudinary.com/demo/image/upload/contactlens/soflens_daily_1.jpg",
    ],
  },
  {
    name: "MyDay Daily Disposable",
    brand: "CooperVision",
    type: "daily disposable",
    color: "red",
    material: "Stenfilcon A",
    waterContent: "54%",
    diameter: 14.2,
    baseCurve: 8.4,
    powerRange: "-12.00 to +8.00",
    uvProtection: true,
    purchasePrice: 20,
    salesPrice: 59,
    stock: 90,
    offer: 0,
    rating: 4.6,
    description:
      "Premium daily disposable lens with Smart Silicone chemistry for breathability.",
    images: [
      "https://res.cloudinary.com/demo/image/upload/contactlens/myday_1day_1.jpg",
    ],
  },
];
