export const allControllablePaths = [
  { path: "/dashboard", role: "employee" },
  { path: "/dashboard/product", role: "employee" },
  { path: "/dashboard/add_frame", role: "employee" },
  { path: "/dashboard/frame_list", role: "employee" },
  { path: "/dashboard/add_lens", role: "employee" },
  { path: "/dashboard/lens_list", role: "employee" },
  { path: "/dashboard/add_contact_lens", role: "employee" },
  { path: "/dashboard/contact_lens_list", role: "employee" },
  { path: "/dashboard/control_user_access", role: "employee" },
  { path: "/dashboard/doctor_profile", role: "doctor" },
  { path: "/dashboard/add_prescription", role: "doctor" },
  { path: "/dashboard/my_prescriptions", role: "doctor" },
  { path: "/dashboard/doctor_schedule", role: "doctor" },
  { path: "/dashboard/add_schedule", role: "doctor" },
  { path: "/dashboard/my_schedule", role: "doctor" },
  { path: "/dashboard/my_patients", role: "doctor" },
];
